# configuration required for DynamoDB Local. Don't store AWS credentials in a configuration file use AWS Secrets Manager instead.
# https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/manage-credentials-using-aws-secrets-manager.html
amazon:
  access:
    key: key
    secretkey: key2
  region: ap-northeast-2
dynamodb:
  endpoint:
    url: http://newmint.lge.com:8000/
